version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /workers
    schedule:
      interval: weekly
    groups:
      workers-development:
        dependency-type: development
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    groups:
      flutter-packages:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
